name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Kill container
        run: docker rm -f my-running-app

      - name: Build
        run: docker build -t my-node-js-app .

      - name: start
        run: docker run -p 6060:6060 -d --rm --name my-running-app my-node-js-app